import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { beforeEach, describe, expect, it } from 'vitest';
import { buildSwapScript, shQuote, spawnSwap, type SwapPlan } from '../../../src/main/update/swap';
import { fakeApp, fakeTools } from './helpers';

const TOOLS = { plutil: '/usr/bin/plutil', codesign: '/usr/bin/codesign', ditto: '/usr/bin/ditto', xattr: '/usr/bin/xattr', open: '/usr/bin/open', sh: '/bin/sh' };

describe('shQuote', () => {
  it('single-quotes everything and escapes embedded quotes', () => {
    expect(shQuote('/Applications/OpenKT.app')).toBe(`'/Applications/OpenKT.app'`);
    expect(shQuote(`/Users/ana/My Apps/Ana's "OpenKT".app`)).toBe(`'/Users/ana/My Apps/Ana'\\''s "OpenKT".app'`);
    expect(shQuote('$(rm -rf ~)`x`')).toBe(`'$(rm -rf ~)\`x\`'`);
    expect(shQuote('')).toBe(`''`);
  });
});

describe('buildSwapScript', () => {
  const plan: SwapPlan = {
    pid: 4242,
    appPath: `/Users/ana/My Apps/Ana's OpenKT.app`,
    newAppPath: `/Users/ana/My Apps/.openkt-update-0.3.9-ab12/OpenKT.app`,
    oldAppPath: `/Users/ana/My Apps/Ana's OpenKT.app.old-1726740000000`,
    stageDir: `/Users/ana/My Apps/.openkt-update-0.3.9-ab12`,
    logPath: '/Users/ana/Library/Application Support/OpenKT/updates/swap.log',
    tools: TOOLS,
  };

  it('is exactly this script for a path with spaces and a quote', () => {
    expect(buildSwapScript(plan)).toBe(
      [
        '#!/bin/sh',
        '# OpenKT self-update. Generated by the running app; runs after it has quit.',
        'PID=4242',
        `APP='/Users/ana/My Apps/Ana'\\''s OpenKT.app'`,
        `NEW='/Users/ana/My Apps/.openkt-update-0.3.9-ab12/OpenKT.app'`,
        `OLD='/Users/ana/My Apps/Ana'\\''s OpenKT.app.old-1726740000000'`,
        `STAGE='/Users/ana/My Apps/.openkt-update-0.3.9-ab12'`,
        `LOG='/Users/ana/Library/Application Support/OpenKT/updates/swap.log'`,
        `OPEN='/usr/bin/open'`,
        'exec >"$LOG" 2>&1',
        'echo "swap: start $(date) pid=$PID"',
        'i=0',
        'while kill -0 "$PID" 2>/dev/null; do',
        '  i=$((i+1))',
        '  if [ "$i" -gt 300 ]; then echo "swap: gave up waiting for pid $PID"; exit 1; fi',
        '  sleep 0.2',
        'done',
        'if [ ! -d "$NEW" ]; then echo "swap: new bundle missing: $NEW"; exit 1; fi',
        'if [ -e "$OLD" ]; then echo "swap: $OLD already exists"; exit 1; fi',
        'if ! /bin/mv "$APP" "$OLD"; then',
        '  echo "swap: could not move the old bundle aside (App Management permission?)"',
        '  "$OPEN" -n "$APP"',
        '  exit 1',
        'fi',
        'if ! /bin/mv "$NEW" "$APP"; then',
        '  echo "swap: could not move the new bundle into place; restoring"',
        '  /bin/mv "$OLD" "$APP"',
        '  "$OPEN" -n "$APP"',
        '  exit 1',
        'fi',
        '/bin/rmdir "$STAGE" 2>/dev/null',
        'echo "swap: installed $APP (previous copy at $OLD)"',
        'exec "$OPEN" -n "$APP"',
        '',
      ].join('\n'),
    );
  });

  it('quotes relaunch options and puts them before the bundle; a rollback deletes the replaced copy', () => {
    const s = buildSwapScript({ ...plan, stageDir: undefined, deleteReplaced: true, openArgs: ['--env', 'OPENKT_SMOKE_OUT=/tmp/a b.json'], waitSeconds: 2 });
    expect(s).toContain(`exec "$OPEN" -n '--env' 'OPENKT_SMOKE_OUT=/tmp/a b.json' "$APP"`);
    expect(s).toContain('if [ "$i" -gt 10 ]');
    expect(s).toContain('/bin/rm -rf "$OLD"');
    expect(s).not.toContain('STAGE');
  });

  it('refuses relative paths, newlines, identical paths and a bad pid', () => {
    expect(() => buildSwapScript({ ...plan, appPath: 'OpenKT.app' })).toThrow(/absolute/);
    expect(() => buildSwapScript({ ...plan, newAppPath: '/a\n/b' })).toThrow(/newline/);
    expect(() => buildSwapScript({ ...plan, oldAppPath: plan.appPath })).toThrow(/differ/);
    expect(() => buildSwapScript({ ...plan, pid: 0 })).toThrow(/pid/);
    expect(() => buildSwapScript({ ...plan, pid: 1 })).toThrow(/pid/);
  });
});

describe('the swap script, executed (fake `open`)', () => {
  let dir = '';
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), `openkt swap "q'`));
    return () => rmSync(dir, { recursive: true, force: true });
  });

  async function run(plan: Omit<SwapPlan, 'pid' | 'logPath' | 'tools'>, tools = fakeTools(join(dir, 'bin'))) {
    const holder = spawn('sleep', ['0.6']);
    const exited = new Promise((r) => holder.once('exit', r));
    await spawnSwap({ ...plan, pid: holder.pid!, logPath: join(dir, 'swap.log'), tools, waitSeconds: 10 }, join(dir, 'swap.sh'));
    await exited;
    for (let i = 0; i < 100 && !/installed|restoring|could not|exists|missing/.test(readFileSync(join(dir, 'swap.log'), 'utf8')); i += 1) await new Promise((r) => setTimeout(r, 50));
    await new Promise((r) => setTimeout(r, 100));
    return { log: readFileSync(join(dir, 'swap.log'), 'utf8'), opened: readFileSync(tools.calls, 'utf8') };
  }

  it('waits for the pid, swaps the bundles, keeps the old copy and relaunches', async () => {
    const apps = join(dir, 'My Apps');
    const app = fakeApp(join(apps, "Ana's OpenKT.app"), { version: '0.3.8' });
    const stage = join(apps, '.openkt-update-0.3.9-ab12');
    fakeApp(join(stage, 'OpenKT.app'), { version: '0.3.9' });
    const old = `${app}.old-1`;
    const { log, opened } = await run({ appPath: app, newAppPath: join(stage, 'OpenKT.app'), oldAppPath: old, stageDir: stage, openArgs: ['--env', 'A=b c'] });
    expect(log).toContain('swap: installed');
    expect(readFileSync(join(app, 'Contents', 'Info.plist'), 'utf8')).toContain('0.3.9');
    expect(readFileSync(join(old, 'Contents', 'Info.plist'), 'utf8')).toContain('0.3.8');
    expect(existsSync(stage)).toBe(false);
    expect(opened.trim()).toBe(`open -n --env A=b c ${app}`);
  });

  it('puts the old bundle back and reopens it when the new one cannot be moved in', async () => {
    const apps = join(dir, 'Apps');
    const app = fakeApp(join(apps, 'OpenKT.app'), { version: '0.3.8' });
    const { log, opened } = await run({ appPath: app, newAppPath: join(apps, 'missing', 'OpenKT.app'), oldAppPath: `${app}.old-2`, stageDir: join(apps, 'missing') });
    expect(log).toContain('new bundle missing');
    expect(readFileSync(join(app, 'Contents', 'Info.plist'), 'utf8')).toContain('0.3.8');
    expect(opened).toBe('');
  });

  it('restores the old bundle if moving the new one fails midway', async () => {
    const apps = join(dir, 'Apps');
    const app = fakeApp(join(apps, 'OpenKT.app'), { version: '0.3.8' });
    // NEW exists but lives on a path mv cannot use as a source into APP: a directory inside APP itself.
    const inner = join(app, 'Contents', 'Nested.app');
    mkdirSync(inner, { recursive: true });
    writeFileSync(join(inner, 'marker'), 'x');
    const { log, opened } = await run({ appPath: app, newAppPath: inner, oldAppPath: `${app}.old-3` });
    expect(log).toContain('restoring');
    expect(existsSync(join(app, 'Contents', 'Info.plist'))).toBe(true);
    expect(existsSync(`${app}.old-3`)).toBe(false);
    expect(opened.trim()).toBe(`open -n ${app}`);
  });

  it('rolls back: the previous copy returns and the broken one is deleted', async () => {
    const apps = join(dir, 'Apps');
    const app = fakeApp(join(apps, 'OpenKT.app'), { version: '0.3.9' });
    const prev = fakeApp(join(apps, 'OpenKT.app.old-5'), { version: '0.3.8' });
    const { log } = await run({ appPath: app, newAppPath: prev, oldAppPath: `${app}.rolledback-6`, deleteReplaced: true });
    expect(log).toContain('removed the replaced copy');
    expect(readFileSync(join(app, 'Contents', 'Info.plist'), 'utf8')).toContain('0.3.8');
    expect(existsSync(prev)).toBe(false);
    expect(existsSync(`${app}.rolledback-6`)).toBe(false);
  });
});
