/**
 * The last step runs OUTSIDE the app: a tiny /bin/sh script, detached, that waits for our process to exit,
 * moves the running bundle aside (`OpenKT.app.old-<ts>`), moves the verified new bundle into place and opens it.
 * If the second move fails it puts the old bundle back and opens that instead, so there is always an app.
 * The old copy is kept: the new version deletes it after its first healthy start (see state.ts). A rollback
 * uses the same script the other way round with `deleteReplaced` (the broken version is removed).
 */
import { spawn } from 'node:child_process';
import { chmod, writeFile } from 'node:fs/promises';
import { SYSTEM_TOOLS, type Tools } from './bundle';

export interface SwapPlan {
  /** Our own pid; the script waits for it to go away. */
  pid: number;
  /** The installed bundle, e.g. /Applications/OpenKT.app */
  appPath: string;
  /** The verified new bundle, on the same volume. */
  newAppPath: string;
  /** Where the running bundle goes: `${appPath}.old-${ts}`. */
  oldAppPath: string;
  /** The staging directory that held `newAppPath`; removed once empty. Absent for a rollback. */
  stageDir?: string;
  logPath: string;
  /** Extra `open` options for the relaunch, placed before the bundle path (the smoke run passes its --env switches). */
  openArgs?: string[];
  /** Seconds to wait for the app to exit before giving up (default 60). */
  waitSeconds?: number;
  /** Rollback: delete the bundle that was moved aside once the swap succeeded. */
  deleteReplaced?: boolean;
  tools?: Tools;
}

/** POSIX single-quote escaping: the only safe way to put an arbitrary path into sh. */
export function shQuote(s: string): string {
  if (s === '') return "''";
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

export function buildSwapScript(plan: SwapPlan): string {
  const t = plan.tools ?? SYSTEM_TOOLS;
  const waitTicks = (plan.waitSeconds ?? 60) * 5;
  if (!Number.isInteger(plan.pid) || plan.pid <= 1) throw new Error('swap: bad pid');
  if (!Number.isInteger(waitTicks) || waitTicks <= 0) throw new Error('swap: bad wait');
  for (const p of [plan.appPath, plan.newAppPath, plan.oldAppPath, plan.logPath, ...(plan.stageDir ? [plan.stageDir] : [])]) {
    if (!p.startsWith('/')) throw new Error(`swap: not an absolute path: ${p}`);
    if (p.includes('\n') || p.includes('\0')) throw new Error('swap: path contains a newline');
  }
  if (new Set([plan.appPath, plan.newAppPath, plan.oldAppPath]).size !== 3) throw new Error('swap: paths must differ');
  const open = ['"$OPEN"', '-n', ...(plan.openArgs ?? []).map(shQuote), '"$APP"'].join(' ');
  return [
    '#!/bin/sh',
    '# OpenKT self-update. Generated by the running app; runs after it has quit.',
    `PID=${plan.pid}`,
    `APP=${shQuote(plan.appPath)}`,
    `NEW=${shQuote(plan.newAppPath)}`,
    `OLD=${shQuote(plan.oldAppPath)}`,
    ...(plan.stageDir ? [`STAGE=${shQuote(plan.stageDir)}`] : []),
    `LOG=${shQuote(plan.logPath)}`,
    `OPEN=${shQuote(t.open)}`,
    'exec >"$LOG" 2>&1',
    'echo "swap: start $(date) pid=$PID"',
    'i=0',
    'while kill -0 "$PID" 2>/dev/null; do',
    '  i=$((i+1))',
    `  if [ "$i" -gt ${waitTicks} ]; then echo "swap: gave up waiting for pid $PID"; exit 1; fi`,
    '  sleep 0.2',
    'done',
    'if [ ! -d "$NEW" ]; then echo "swap: new bundle missing: $NEW"; exit 1; fi',
    'if [ -e "$OLD" ]; then echo "swap: $OLD already exists"; exit 1; fi',
    'if ! /bin/mv "$APP" "$OLD"; then',
    '  echo "swap: could not move the old bundle aside (App Management permission?)"',
    `  ${open}`,
    '  exit 1',
    'fi',
    'if ! /bin/mv "$NEW" "$APP"; then',
    '  echo "swap: could not move the new bundle into place; restoring"',
    '  /bin/mv "$OLD" "$APP"',
    `  ${open}`,
    '  exit 1',
    'fi',
    ...(plan.stageDir ? ['/bin/rmdir "$STAGE" 2>/dev/null'] : []),
    ...(plan.deleteReplaced ? ['/bin/rm -rf "$OLD"', 'echo "swap: installed $APP (removed the replaced copy)"'] : ['echo "swap: installed $APP (previous copy at $OLD)"']),
    `exec ${open}`,
    '',
  ].join('\n');
}

/** Writes the script and starts it detached; it outlives us. Returns once it is spawned. */
export async function spawnSwap(plan: SwapPlan, scriptPath: string): Promise<void> {
  const t = plan.tools ?? SYSTEM_TOOLS;
  await writeFile(scriptPath, buildSwapScript(plan), { mode: 0o700 });
  await chmod(scriptPath, 0o700);
  await new Promise<void>((resolve, reject) => {
    const child = spawn(t.sh, [scriptPath], { detached: true, stdio: 'ignore', cwd: '/' });
    child.once('error', reject);
    child.once('spawn', () => {
      child.unref();
      resolve();
    });
  });
}
